config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
  get '/about', to: 'pages#about'
  post 'feedback', to: 'pages#submit_feedback'
  get 'feedback', to: 'pages#feedback'

  resources :predictors, only: [:index, :show, :new, :create] do
    resources :predictions, only: [:new, :create]
  end

  resources :predictions, only: [:index, :show, :edit, :update, :destroy] do
    resources :outcomes, only: [:new, :create]
    resources :reports, only: [:new, :create]
    resources :comments, only: [:new, :create]
  end

  resources :outcomes, only: [:show, :edit, :update, :destroy, :index] do
    resources :comments, only: [:new, :create]
    resources :reports, only: [:new, :create]
  end

  resources :reports, only: [:index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:destroy]

  post '/predictions/:id', to: 'predictions#vote', as: 'prediction_vote'
  post '/outcomes/:id', to: 'outcomes#vote', as: 'outcome_vote'

end

app/models/prediction.rb
class Prediction < ApplicationRecord
  belongs_to :predictor
  has_many :reports, as: :reportable, dependent: :delete_all
  has_many :comments, as: :commentable, dependent: :delete_all
  has_many :outcomes, dependent: :delete_all 
  validates :title, :body, :duedate, presence: true
  acts_as_votable
  belongs_to :user
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  before_action :set_prediction, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, only: [:new, :create, :vote ]
  before_action :owner_or_admin?, only: [ :edit, :update, :destroy ]

  # GET /predictions or /predictions.json
  def index
    if params[:query] == "due"
      rawpredictions = Prediction.where("duedate < ?", Date.today)
    elsif params[:query] == "due-no-outcome"
      rawpredictions = Prediction.left_outer_joins(:outcomes).where(outcomes: { id: nil }).where("duedate < ?", Date.today)
    elsif params[:query] == "users"
      rawpredictions = current_user.predictions
    else
      rawpredictions = Prediction.all
    end
    rawpredictions = rawpredictions.order(:created_at)
    @predictions = rawpredictions.paginate(page: params[:page], per_page: 10)
  end

  # GET /predictions/1 or /predictions/1.json
  def show
    @predictor = @prediction.predictor
    @outcomes = @prediction.outcomes.order(cached_weighted_score: :desc)
    @comments = @prediction.comments.order(:created_at)
  end

  # GET /predictions/new
  def new
    @predictor = Predictor.find(params[:predictor_id])
    @prediction = @predictor.predictions.build()
  end

  # GET /predictions/1/edit
  def edit
  end

  # POST /predictions or /predictions.json
  def create
    @predictor = Predictor.find(params[:predictor_id])
    @prediction = @predictor.predictions.build(prediction_params)
    @prediction.update(user_id: current_user.id)
    @prediction.liked_by current_user
    respond_to do |format|
      if @prediction.save
        format.html { redirect_to prediction_path(@prediction), notice: "Prediction was successfully created." }
        # format.html { redirect_to root_path, notice: "Prediction was successfully created." }
        format.json { render :show, status: :created, location: @prediction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /predictions/1 or /predictions/1.json
  def update
    respond_to do |format|
      if @prediction.update(prediction_params)
        format.html { redirect_to prediction_path(@prediction), notice: "Prediction was successfully updated." }
        format.json { render :show, status: :ok, location: @prediction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prediction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /predictions/1 or /predictions/1.json
  def destroy
    @prediction.destroy!

    respond_to do |format|
      format.html { redirect_to predictions_url, notice: "Prediction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def vote

    @prediction = Prediction.find(params[:votable_id])
    @votedirection = params[:vote]
    @currentvote = current_user.voted_as_when_voted_for @prediction

    if @currentvote == true && @votedirection == "Upvote"
      @prediction.unliked_by current_user
    elsif @votedirection == "Upvote"
      @prediction.liked_by current_user
    elsif @currentvote == false && @votedirection == "Downvote"
      @prediction.undisliked_by current_user
    elsif @votedirection == "Downvote"
      @prediction.disliked_by current_user
    end

    redirect_back(fallback_location: root_path)
    # render partial: 'app/views/layouts/voting.html.erb', locals: { votable: @prediction, destination: prediction_vote_path(@prediction) }

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_prediction
    @prediction = Prediction.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def prediction_params
    params.require(:prediction).permit(:title, :body, :query, :duedate, :votable_id, :vote)
  end

  def owner_or_admin?
    authenticate_user!
    unless current_user.admin? || @prediction.user_id == current_user.id then
      flash[:alert] = "You are not authorized to view this page."
      redirect_to root_path 
    end
  end

end

app/helpers/predictions_helper.rb
module PredictionsHelper
end

app/views/predictions/_form.html.erb
<% if @prediction.errors.any? %>
<div class="notification is-warning">
  <%= pluralize(@prediction.errors.count, "error") %> prohibited this prediction from being saved:
  <ul>
    <% @prediction.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_with(model: [@predictor, @prediction], class: "form" ) do |form| %>
<%= form.label :title, style: "display: block", class: "label" %>
<div class="field">
  <%= form.text_area :title, class: "input", type: "text" %>
</div>
<%= form.label :body, style: "display: block", class: "label" %>
<div class="field">
  <%= form.text_area :body, class: "textarea" %>
</div>
<%= form.label "Due Date", style: "display: block", class: "label" %>
<div class="field">
  <%= form.date_field :duedate, class: "input", max: Date.today + 36500 %>
</div>
<%= form.submit class: "button is-link" %>
<% end %>

app/views/predictions/_prediction.html.erb
<div class="card">
  <div class="card-content">
    <div class="columns">

      <div class="column is-1">
	<%= render template: "layouts/voting", locals: { votable: prediction, destination: prediction_vote_path(prediction) } %>
      </div>

      <div class="column">
	"<%= link_to prediction.title, prediction_path(prediction) %>" by 
	<%= prediction.duedate %>
	<br>
	<em>Created by <%= User.find(prediction.user_id).username %> on <%= prediction.created_at.to_date %></em>
      </div>
    </div>
  </div>
</div>

app/views/predictions/_predictionindex.html.erb
<div class="card">
  <div class="card-content">
    <div class="columns">
      <div class="column is-1">
	<%= render template: "layouts/voting", locals: { votable: predictionindex, destination: prediction_vote_path(predictionindex) } %>
      </div>
      <div class="column">
	"<%= link_to predictionindex.title, prediction_path(predictionindex) %>" by 
	<%= predictionindex.duedate %>. 
	(<%= link_to predictionindex.predictor.title, predictor_path(predictionindex.predictor) %>)
	<br>
	<em>Created by <%= User.find(predictionindex.user_id).username %> on <%= predictionindex.created_at.to_date %></em>
      </div>

    </div>
  </div>
</div>

app/views/predictions/edit.html.erb
<div class="block">
  <%= render "form", prediction: @prediction %>
  <%= link_to "Cancel", @prediction, class: "button is-link is-light" %>
</div>

app/views/predictions/index.html.erb
<div class="section">
  <div class="block">

    <% if params[:query].nil? then %>
    <%= link_to 'All', predictions_path, class: "button is-primary" %> 
    <% else %>
    <%= link_to 'All', predictions_path, class: "button is-light" %> 
    <% end %>

    <% if params[:query] == "due" %>
    <%= link_to 'Due', predictions_path(query: "due"), class: "button is-primary" %> 
    <% else %>
    <%= link_to 'Due', predictions_path(query: "due"), class: "button is-light" %> 
    <% end %>

    <% if params[:query] == "due-no-outcome" %>
    <%= link_to 'Due - no outcome yet', predictions_path(query: "due-no-outcome"), class: "button is-primary" %> 
    <% else %>
    <%= link_to 'Due - no outcome yet', predictions_path(query: "due-no-outcome"), class: "button is-light" %> 
    <% end %>

    <% if user_signed_in? %>
    <% if params[:query] == "users" %>
    <%= link_to 'My Predictions', predictions_path(query: "users"), class: "button is-primary" %>
    <% else %>
    <%= link_to 'Your Predictions', predictions_path(query: "users"), class: "button is-light" %>
    <% end %>
    <% end %>

  </div>

  <%= render partial: "predictionindex", collection: @predictions %>

  <div class="digg_pagination">
    <%= will_paginate @predictions, :container => false %>
  </div>

</div>

app/views/predictions/new.html.erb
<div class="block">
  <div class="content is-small">
    All predictions must: 
    <ul>
      <li>Be specific and observable.</li>
      <li>Have a specific timeframe.</li>
      <li>Include a link to the direct source of the prediction.</li>
      <li>Include a quote of the original wording of the prediction (in case the source link is taken down).</li>
    </ul>
  </div>
</div>
<div class="block">
  <%= render "form", prediction: @prediction %>
  <%= link_to "Cancel", @prediction, class: "button is-link is-light" %>
</div>

app/views/predictions/show.html.erb
<div class="section">
  <div class="block">
    <%= link_to "<< Back to " + @predictor.title, predictor_path(@predictor) %>
  </div>
  <%= render @prediction %>

  <div class="block">
    <%= simple_format(@prediction.body) %>
  </div>

  <div class="block">
    <%= link_to 'Report this prediction', new_prediction_report_path(@prediction) %>
    <% if user_signed_in? && (@prediction.user.id == current_user.id || current_user.admin?) %>
    | <%= link_to "Edit this prediction", edit_prediction_path(@prediction) %> | 
    <%= link_to "Destroy this prediction", @prediction, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    <% end %>
  </div>

  <h5 class="title is-5">Comments</h5>

  <table class="table is-bordered is-fullwidth">
    <% @comments.each do |comment| %>
    <tr>
      <td>
	<%= render comment %>
      </td>
    </tr>
    <% end %>
  </table>

  <div class="block">
    <%= link_to 'Add New Comment', new_prediction_comment_path(@prediction), class: "button is-link"  %>
  </div>

  <div class="block">
  </div>

  <% if @prediction.duedate < Date.today %>
  <div class="title is-5">Outcomes</div>

  <% @outcomes.each do |outcome| %>
  <%= render outcome %>
  <% end %>

  <div class="block">
    <%= link_to 'Lodge an outcome for this prediction', new_prediction_outcome_path(@prediction), class: "button is-link" %>
  </div>
  <% else %>
  Return after <%= @prediction.duedate.strftime("%B %d, %Y") %> to lodge an outcome.
  <% end %>    

</div>