config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
  get '/about', to: 'pages#about'
  post 'feedback', to: 'pages#submit_feedback'
  get 'feedback', to: 'pages#feedback'

  resources :predictors, only: [:index, :show, :new, :create] do
    resources :predictions, only: [:new, :create]
  end

  resources :predictions, only: [:index, :show, :edit, :update, :destroy] do
    resources :outcomes, only: [:new, :create]
    resources :reports, only: [:new, :create]
    resources :comments, only: [:new, :create]
  end

  resources :outcomes, only: [:show, :edit, :update, :destroy, :index] do
    resources :comments, only: [:new, :create]
    resources :reports, only: [:new, :create]
  end

  resources :reports, only: [:index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:destroy]

  post '/predictions/:id', to: 'predictions#vote', as: 'prediction_vote'
  post '/outcomes/:id', to: 'outcomes#vote', as: 'outcome_vote'

end

app/models/outcome.rb
class Outcome < ApplicationRecord
  belongs_to :prediction 
  enum result: { "Successful" => 0, "Unsuccessful" => 1, "Inconclusive" => 2 }
  has_many :reports, as: :reportable, dependent: :delete_all 
  has_many :comments, as: :commentable, dependent: :delete_all
  validates :body, :result, presence: true
  acts_as_votable
  belongs_to :user
end

app/controllers/outcomes_controller.rb
class OutcomesController < ApplicationController
  before_action :set_outcome, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, only: [:new, :create, :vote ]
  before_action :owner_or_admin?, only: [ :edit, :update, :destroy ]

  def index
    @outcomes = Outcome.all.paginate(page: params[:page], per_page: 10)
  end

  # GET /outcomes/1 or /outcomes/1.json
  def show
    @comments = @outcome.comments.order(:created_at)
  end

  # GET /outcomes/new
  def new
    @prediction = Prediction.find(params[:prediction_id])
    @outcome = @prediction.outcomes.build
  end

  # GET /outcomes/1/edit
  def edit
  end

  # POST /outcomes or /outcomes.json
  def create
    @prediction = Prediction.find(params[:prediction_id])
    @outcome = @prediction.outcomes.build(outcome_params)
    @outcome.update(user_id: current_user.id)
    @outcome.liked_by current_user
    respond_to do |format|
      if @outcome.save
        format.html { redirect_to prediction_path(@prediction), notice: "Outcome was successfully created." }
        format.json { render :show, status: :created, location: @outcome }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outcomes/1 or /outcomes/1.json
  def update
    @prediction = @outcome.prediction
    respond_to do |format|
      if @outcome.update(outcome_params)
        format.html { redirect_to prediction_path(@prediction), notice: "Outcome was successfully updated." }
        format.json { render :show, status: :ok, location: @outcome }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outcomes/1 or /outcomes/1.json
  def destroy
    @outcome.destroy!
    @prediction = @outcome.prediction

    respond_to do |format|
      format.html { redirect_to prediction_path(@prediction), notice: "Outcome was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def vote
    @outcome = Outcome.find(params[:votable_id])
    @votedirection = params[:vote]
    @currentvote = current_user.voted_as_when_voted_for @outcome

    if @currentvote == true && @votedirection == "Upvote"
      @outcome.unliked_by current_user
    elsif @votedirection == "Upvote"
      @outcome.liked_by current_user
    elsif @currentvote == false && @votedirection == "Downvote"
      @outcome.undisliked_by current_user
    elsif @votedirection == "Downvote"
      @outcome.disliked_by current_user
    end

    redirect_back(fallback_location: root_path)

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outcome
      @outcome = Outcome.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def outcome_params
      params.require(:outcome).permit(:result, :body)
    end

    def owner_or_admin?
      authenticate_user!
      unless current_user.admin? || @outcome.user_id == current_user.id then
        flash[:alert] = "You are not authorized to view this page."
        redirect_to root_path 
      end
    end

end

app/helpers/outcomes_helper.rb
module OutcomesHelper
end

app/views/outcomes/_form.html.erb
<% if @outcome.errors.any? %>
<div class="notification is-warning">
  <%= pluralize(@outcome.errors.count, "error") %> prohibited this outcome from being saved:
  <ul>
    <% @outcome.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_with(model: [@prediction, @outcome], class: "form" ) do |form| %>
<%= form.label :title, style: "display: block", class: "label" %>
<div class="field">
<div class="select">
<%= form.select :result, Outcome.results.keys.map { |result| [result.titleize, result] }, { prompt: 'Select a Result' } %>
</div>
</div>

<%= form.label :body, class: "label" %>
<div class="field">
<%= form.text_area :body, class: "textarea" %>
</div>
<%= form.submit class: "button is-link" %>
<% end %>

app/views/outcomes/_outcome.html.erb
<div class="columns">

  <div class="column is-1">
    <%= render template: "layouts/voting", locals: { votable: outcome, destination: outcome_vote_path(outcome) } %>
  </div>
  <div class="column">
    <strong><%= link_to outcome.result, outcome %></strong>
  </div>

</div>

<div class="block">
  <%= simple_format(outcome.body) %>
</div>

<div class="block">
  <em>Created by <%= User.find(outcome.user_id).username %> on <%= outcome.created_at.to_date %></em>
</div>

app/views/outcomes/edit.html.erb
<div class="block">
  <%= render "form", outcome: @outcome %>
  <%= link_to "Cancel", @outcome, class: "button is-link is-light" %>
</div>

app/views/outcomes/index.html.erb
<div class="section">
  <% @outcomes.each do |outcome| %>
  <div class="card">
    <div class="card-content">
      <%= link_to outcome.result + ": " + outcome.prediction.title, outcome_path(outcome) %>
    </div>
  </div>
  <% end %>
  <div class="digg_pagination">
    <%= will_paginate @outcomes, :container => false  %>
  </div>
</div>

app/views/outcomes/new.html.erb
<div class="block">
  <%= render "form", outcome: @outcome %>
  <%= link_to "Cancel", @outcome.prediction, class: "button is-link is-light" %>
</div>

app/views/outcomes/show.html.erb
<div class="section">
  <div class="block">
    <%= link_to "<< Back to " + @outcome.prediction.title, prediction_path(@outcome.prediction) %>
  </div>
  <%= render @outcome %>

  <div class="block">
    <%= link_to 'Lodge a report', new_outcome_report_path(@outcome) %>
    <% if user_signed_in? && (@outcome.user.id == current_user.id || current_user.admin?) %>
    | <%= link_to "Edit this outcome", edit_outcome_path(@outcome) %> | 
    <%= link_to "Destroy this outcome", @outcome, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    <% end %>
  </div>

  <h5 class="title is-5">Comments</h5>

  <table class="table is-bordered is-fullwidth">
    <% @comments.each do |comment| %>
    <tr>
      <td>
	<%= render comment %>
      </td>
    </tr>
    <% end %>
  </table>

  <div class="block">
    <%= link_to 'Add New Comment', new_outcome_comment_path(@outcome) %>
  </div>
</div>