config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
  get '/about', to: 'pages#about'
  post 'feedback', to: 'pages#submit_feedback'
  get 'feedback', to: 'pages#feedback'

  resources :predictors, only: [:index, :show, :new, :create] do
    resources :predictions, only: [:new, :create]
  end

  resources :predictions, only: [:index, :show, :edit, :update, :destroy] do
    resources :outcomes, only: [:new, :create]
    resources :reports, only: [:new, :create]
    resources :comments, only: [:new, :create]
  end

  resources :outcomes, only: [:show, :edit, :update, :destroy, :index] do
    resources :comments, only: [:new, :create]
    resources :reports, only: [:new, :create]
  end

  resources :reports, only: [:index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:destroy]

  post '/predictions/:id', to: 'predictions#vote', as: 'prediction_vote'
  post '/outcomes/:id', to: 'outcomes#vote', as: 'outcome_vote'

end

app/models/report.rb
class Report < ApplicationRecord

  enum reason: {"Not directly quoted" => 0,
                "Not objectively measurable" => 1,
                "No objective time frame" => 2,
                "No original source/citation" => 3,
                "Duplicate" => 4,
                "Misleading/inaccurate" => 5,
                "Replacement link" => 6,
                "Offensive content" => 7,
                "Other" => 8}

  enum status: {"Pending" => 0,
                "Upheld" => 1,
                "Dismissed" => 2}
  
  belongs_to :reportable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :delete_all
  validates :body, :reason, presence: true
  belongs_to :user

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [ :show, :edit, :update, :destroy ]
  before_action :set_reportable, only: [ :new, :create, :edit, :update ]
  before_action :authenticate_user!
  before_action :is_admin?, except: [ :new, :create ]

  # GET /reports or /reports.json
  def index
    if params[:query] 
      rawreports = Report.where(status: params[:query])
    else
      rawreports = Report.all
    end
    rawreports = rawreports.order(:created_at)
    @reports = rawreports.paginate(page: params[:page], per_page: 10)
  end

  # GET /reports/1 or /reports/1.json
  def show
    @comments = @report.comments
  end

  # GET /reports/new
  def new
    @report = @reportable.reports.build
    if @report.reportable_type == "Prediction"
      @reason_list = Report.reasons.keys.map { |reason| [reason.titleize, reason] }
    elsif @report.reportable_type == "Outcome"
      @reason_list = Report.reasons.keys.drop(5).map { |reason| [reason.titleize, reason] }
    end
  end

  # GET /reports/1/edit
  def edit
    if @report.reportable_type == "Prediction"
      @reason_list = Report.reasons.keys.map { |reason| [reason.titleize, reason] }
    elsif @report.reportable_type == "Outcome"
      @reason_list = Report.reasons.keys.drop(5).map { |reason| [reason.titleize, reason] }
    end
  end

  # POST /reports or /reports.json
  def create
    @report = @reportable.reports.build(report_params)
    @report.update(user_id: current_user.id)
    if @report.reportable_type == "Prediction"
      destination = prediction_path(@reportable)
    elsif @report.reportable_type == "Outcome"
      destination = prediction_path(@reportable.prediction)
    end

    if @report.reportable_type == "Prediction"
      @reason_list = Report.reasons.keys.map { |reason| [reason.titleize, reason] }
    elsif @report.reportable_type == "Outcome"
      @reason_list = Report.reasons.keys.drop(5).map { |reason| [reason.titleize, reason] }
    end

    respond_to do |format|
      if @report.save
        format.html { redirect_to destination, notice: "Report was successfully created." }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1 or /reports/1.json
  def update
    if @report.reportable_type == "Prediction"
      destination = prediction_path(@reportable)
    elsif @report.reportable_type == "Outcome"
      destination = prediction_path(@reportable.prediction)
    end

    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to destination, notice: "Report was successfully updated." }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1 or /reports/1.json
  def destroy
    @report.destroy!

    respond_to do |format|
      format.html { redirect_to reports_url, notice: "Report was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def report_params
    params.require(:report).permit(:reason, :body, :status)
  end

  def set_reportable
    if @report
      @reportable = @report.reportable
    elsif params[:prediction_id]
      @reportable = Prediction.find(params[:prediction_id]) 
    elsif params[:outcome_id]
      @reportable = Outcome.find(params[:outcome_id]) 
    end
  end

  def is_admin?
    unless current_user.admin? then
      flash[:alert] = "You are not authorized to view this page."
      redirect_to root_path 
    end
  end

end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_editform.html.erb
<% if report.errors.any? %>
<div class="notification is-warning">
  <%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:
  <ul>
    <% report.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_with(model: @report, class: "form") do |form| %>
<div class="field">
  <%= form.select :reason, @reason_list, { prompt: 'Select a Reason' } %>
</div>

<%= form.label :body, style: "display: block", class: "label"  %>
<div class="field">
  <%= form.text_area :body, class: "textarea" %>
</div>
<% if current_user.admin? %>
<div class="field">
  <%= form.select :status, Report.statuses.keys, { prompt: 'Select a Status' } %>
</div>
<% else %>
<%= form.hidden_field :status, value: "Pending" %>
<% end %>
<%= form.submit class: "button is-link" %>
<% end %>

app/views/reports/_form.html.erb
<% if report.errors.any? %>
<div class="notification is-warning">
  <%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:
  <ul>
    <% report.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_with(model: [@reportable, @report], class: "form") do |form| %>
<div class="field">
  <%= form.select :reason, @reason_list, { prompt: 'Select a Reason' } %>
</div>

<%= form.label :body, style: "display: block", class: "label"  %>
<div class="field">
  <%= form.text_area :body, class: "textarea" %>
</div>
<% if current_user.admin? %>
<div class="field">
  <%= form.select :status, Report.statuses.keys, { prompt: 'Select a Status' } %>
</div>
<% else %>
<%= form.hidden_field :status, value: "Pending" %>
<% end %>
<%= form.submit class: "button is-link" %>
<% end %>

app/views/reports/_report.html.erb
<strong>Reportable:</strong> <%= link_to report.reportable %>
<br>
<strong>Reason:</strong> <%= report.reason %>
<br>
<strong>Body:</strong> <%= report.body %>
<br>
<strong>Status:</strong> <%= report.status %>
<br>
<em>Created by <%= User.find(report.user_id).username %> on <%= report.created_at.to_date %></em>

app/views/reports/edit.html.erb
<h1>Editing report</h1>

<%= render "editform", report: @report %>

<br>

<div>
  <%= link_to "Show this report", @report %> |
  <%= link_to "Back to reports", reports_path %>
</div>

app/views/reports/index.html.erb
<div class="section">
  <%= link_to 'All Reports', reports_path() %> |
  <%= link_to 'Pending Reports', reports_path(query: "Pending") %> |
  <%= link_to 'Upheld Reports', reports_path(query: "Upheld") %> |
  <%= link_to 'Dismissed Reports', reports_path(query: "Dismissed") %>
  <br>
  <br>
  <% @reports.each do |report| %>
  <div class="block">
    <%= render report %>
    <br>
    <%= link_to "Show this report", report %>
  </div>
  <% end %>
  <div class="digg_pagination">
    <%= will_paginate @reports, :container => false %>
  </div>
</div>

app/views/reports/new.html.erb
<div class="block">
  <%= render "form", report: @report %>
  <%= link_to "Cancel", @report.reportable, class: "button is-link is-light" %>
</div>

app/views/reports/show.html.erb
<%= render @report %>

<div class="block">
  <%= link_to "Edit this report", edit_report_path(@report) %> |
  <%= link_to "Destroy this report", @report, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "bulma-delete-mixin is-large" %>
</div>

<div class="title is-5">Comments:</div>

<% @comments.each do |comment| %>
<div class="block">
  <%= comment.created_at %>
  <br>
  <%= comment.body %>
</div>
<% end %>

<%= link_to 'Add New Comment', new_report_comment_path(@report) %>