config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  root "pages#home"
  get '/about', to: 'pages#about'
  post 'feedback', to: 'pages#submit_feedback'
  get 'feedback', to: 'pages#feedback'

  resources :predictors, only: [:index, :show, :new, :create] do
    resources :predictions, only: [:new, :create]
  end

  resources :predictions, only: [:index, :show, :edit, :update, :destroy] do
    resources :outcomes, only: [:new, :create]
    resources :reports, only: [:new, :create]
    resources :comments, only: [:new, :create]
  end

  resources :outcomes, only: [:show, :edit, :update, :destroy, :index] do
    resources :comments, only: [:new, :create]
    resources :reports, only: [:new, :create]
  end

  resources :reports, only: [:index, :show, :edit, :update, :destroy] do
    resources :comments, only: [:new, :create]
  end

  resources :comments, only: [:destroy]

  post '/predictions/:id', to: 'predictions#vote', as: 'prediction_vote'
  post '/outcomes/:id', to: 'outcomes#vote', as: 'outcome_vote'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prediction Tracker: Track predictions, keep experts accountable.</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">

    <script>
      document.addEventListener("turbo:load", () => {
	  // Get all "navbar-burger" elements
	  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);
	  // Add a click event on each of them
	  $navbarBurgers.forEach( el => {
	      el.addEventListener('click', () => {
		  // Get the target from the "data-target" attribute
		  const target = el.dataset.target;
		  const $target = document.getElementById(target);
		  // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
		  el.classList.toggle('is-active');
		  $target.classList.toggle('is-active');
	      });
	  });
      });
      // Function to save scroll position and refresh
      function saveScrollPosition() {
	  sessionStorage.setItem('scrollPosition', window.scrollY);
      }

      // Function to restore scroll position after page load
      document.addEventListener('turbo:load', (event) => {
	  if (sessionStorage.getItem('scrollPosition')) {
      window.scrollTo(0, parseInt(sessionStorage.getItem('scrollPosition')));
      sessionStorage.removeItem('scrollPosition');
      }
      });
    </script>
  </head>

  <body>

    <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
	<%= link_to 'Prediction Tracker', root_path, class: "navbar-item is-active has-text-weight-bold" %> 
	<a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navMenu">
	  <span aria-hidden="true"></span>
	  <span aria-hidden="true"></span>
	  <span aria-hidden="true"></span>
	</a>
      </div>

      <div class="navbar-menu" id="navMenu">
	<div class="navbar-start">
	  <%= link_to 'Home', root_path, class: "navbar-item" %> 
	  <%= link_to 'About', about_path, class: "navbar-item" %> 
	  <%= link_to 'Predictors', predictors_path, class: "navbar-item" %> 
	  <%= link_to 'Predictions', predictions_path, class: "navbar-item" %> 
	  <%= link_to 'Outcomes', outcomes_path, class: "navbar-item" %> 
	  <% if user_signed_in? then %> 
	  <%= link_to 'Feedback', feedback_path, class: "navbar-item" %> 
	  <% end %>
	  <% if user_signed_in? && current_user.admin? then %> 
	  <%= link_to 'Show Reports', reports_path, class: "navbar-item" %> 
	  <% end %>
	</div>

	<div class="navbar-end">
	  <% if user_signed_in? %>
	  <div class="navbar-item">
	    Signed in as <%= current_user.username %>
	  </div>
	  <%= link_to("Sign Out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "navbar-item" ) %>
	  <% else %>
	  <%= link_to("Sign in", new_user_session_url, class: "navbar-item") %>
	  <%= link_to("Sign up", new_user_registration_url, class: "navbar-item") %>
	  <% end %>
	</div>
      </div>
    </nav>

    <% if notice %>
    <div class="notification is-success">
      <%= notice %>
    </div>
    <% end %>

    <% if alert %>
    <div class="notification is-danger">
      <%= alert %>
    </div>
    <% end %>

    <div class="section">
      <%= yield %>
    </div>
    <%# if Rails.env.development? then console end %>

  </body>
</html>

app/views/layouts/voting.html.erb
<div style="text-align: center;" class="">
  <%= form_with url: destination, data: { turbo_method: :post } do |form| %>
  <%= form.hidden_field :vote, value: "Upvote" %>
  <%= form.hidden_field :votable_id, value: votable.id %>
  <% if user_signed_in? && current_user.voted_as_when_voted_for(votable) then %>
  <%= form.submit("&#x25B3;".html_safe, style: 'background-color: palegreen;', onclick: 'saveScrollPosition()') %>
  <% else %>
  <%= form.submit "&#x25B3;".html_safe, onclick: 'saveScrollPosition()' %>
  <% end %>
  <% end %>
</div>
<div style="text-align: center;" class="">
  <%= votable.weighted_score %>
</div>
<div style="text-align: center;" class="">
  <%= form_with url: destination, data: { turbo_method: :post } do |form| %>
  <%= form.hidden_field :vote, value: "Downvote" %>
  <%= form.hidden_field :votable_id, value: votable.id %>
  <% if user_signed_in? && current_user.voted_as_when_voted_for(votable) == false then %>
  <%= form.submit "&#x25BD;".html_safe, style: 'background-color: pink;', onclick: 'saveScrollPosition()' %>
  <% else %>
  <%= form.submit "&#x25BD;".html_safe, onclick: 'saveScrollPosition()' %>
  <% end %>
  <% end %>
</div>